# Generated by Django 5.2.6 on 2025-10-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ligou', models.IntegerField(blank=True, max_length=10, null=True)),
                ('desligou', models.IntegerField(blank=True, max_length=10, null=True)),
                ('temporizador', models.DateTimeField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
