# Generated by Django 5.2.6 on 2025-10-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='12345')),
            ],
        ),
        migrations.AlterField(
            model_name='historico',
            name='desligou',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='ligou',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
